name: flutter_windowmanager_plus
description: "A Flutter plugin for manipulating Android WindowManager LayoutParams"
version: 1.0.0+1
repository: https://github.com/ijashuzain/flutter_windowmanager_plus


environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.vexellab.flutter_windowmanager_plus
        pluginClass: FlutterWindowManagerPlugin
